# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestNewgroup():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_newgroup(self):
    self.driver.get("http://localhost/iwebsns/main.php")
    self.driver.set_window_size(1084, 738)
    self.driver.find_element(By.CSS_SELECTOR, ".app_group span").click()
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.LINK_TEXT, "创建群组").click()
    self.driver.find_element(By.ID, "group_name").click()
    self.driver.find_element(By.ID, "group_name").send_keys("wuji")
    self.driver.find_element(By.ID, "group_resume").click()
    self.driver.find_element(By.ID, "group_resume").send_keys("wuji")
    self.driver.find_element(By.NAME, "group_join_type").click()
    dropdown = self.driver.find_element(By.NAME, "group_join_type")
    dropdown.find_element(By.XPATH, "//option[. = '验证加入']").click()
    self.driver.find_element(By.NAME, "group_join_type").click()
    self.driver.find_element(By.ID, "tag").click()
    self.driver.find_element(By.ID, "tag").send_keys("wuji")
    self.driver.find_element(By.ID, "group_type").click()
    dropdown = self.driver.find_element(By.ID, "group_type")
    dropdown.find_element(By.XPATH, "//option[. = '极品音乐']").click()
    self.driver.find_element(By.ID, "group_type").click()
    self.driver.find_element(By.ID, "group_logo").click()
    self.driver.find_element(By.ID, "group_logo").send_keys("C:\\fakepath\\monster.png")
    self.driver.find_element(By.ID, "UploadButton").click()
  
