# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_1(self):
    self.driver.get("http://localhost/iwebsns/main.php")
    self.driver.set_window_size(1084, 738)
    self.driver.find_element(By.CSS_SELECTOR, ".app_vote span").click()
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.LINK_TEXT, "测试投票").click()
    self.driver.find_element(By.LINK_TEXT, "删除本投票").click()
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, ".mini_button:nth-child(1)").click()
  
